/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) double_joints_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

/* double_joints_expl_vde_adj:(i0[4],i1[4],i2[2],i3[0])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][2] : 0;
  a3=(a1*a2);
  a4=3.3613445378151261e+00;
  a5=arg[1]? arg[1][3] : 0;
  a4=(a4*a5);
  a6=1.6806722689075630e+00;
  a7=arg[1]? arg[1][2] : 0;
  a8=(a6*a5);
  a9=(a1*a8);
  a5=(a5+a9);
  a7=(a7-a5);
  a5=2.9749999999999999e-01;
  a0=sin(a0);
  a9=casadi_sq(a0);
  a10=1.5966386554621848e-01;
  a11=(a10*a1);
  a12=(a11*a1);
  a9=(a9+a12);
  a5=(a5+a9);
  a9=(a7/a5);
  a12=(a1*a9);
  a13=(a6*a12);
  a4=(a4-a13);
  a13=(a3*a4);
  a14=5.0000000000000000e-01;
  a15=arg[0]? arg[0][3] : 0;
  a16=(a15+a2);
  a17=(a14*a16);
  a17=(a3+a17);
  a18=(a17*a4);
  a13=(a13-a18);
  a18=(a10*a12);
  a18=(a8+a18);
  a19=(a15*a18);
  a13=(a13+a19);
  a19=(a16*a12);
  a13=(a13-a19);
  a19=(a2*a13);
  a20=(a0+a0);
  a21=arg[2]? arg[2][0] : 0;
  a22=arg[2]? arg[2][1] : 0;
  a23=(a15*a3);
  a24=(a16*a17);
  a23=(a23-a24);
  a24=(a0*a23);
  a25=(a0*a2);
  a26=(a16*a25);
  a27=(a15*a25);
  a27=(a10*a27);
  a26=(a26-a27);
  a27=(a25*a17);
  a28=(a3*a25);
  a27=(a27-a28);
  a27=(a22-a27);
  a6=(a6*a27);
  a26=(a26+a6);
  a6=(a1*a26);
  a24=(a24+a6);
  a22=(a22+a24);
  a21=(a21-a22);
  a21=(a21/a5);
  a5=(a21/a5);
  a5=(a5*a7);
  a20=(a20*a5);
  a19=(a19-a20);
  a23=(a23*a9);
  a19=(a19-a23);
  a19=(a1*a19);
  a23=(a0*a9);
  a16=(a16*a23);
  a15=(a15*a23);
  a15=(a16-a15);
  a2=(a2*a15);
  a21=(a21*a8);
  a11=(a11*a5);
  a21=(a21+a11);
  a5=(a1*a5);
  a10=(a10*a5);
  a21=(a21+a10);
  a26=(a26*a9);
  a21=(a21+a26);
  a2=(a2-a21);
  a2=(a0*a2);
  a19=(a19-a2);
  if (res[0]!=0) res[0][1]=a19;
  a0=(a0*a13);
  a17=(a17*a23);
  a12=(a25*a12);
  a17=(a17-a12);
  a12=(a25*a4);
  a16=(a16-a12);
  a14=(a14*a16);
  a17=(a17+a14);
  a0=(a0+a17);
  a1=(a1*a15);
  a0=(a0+a1);
  a1=arg[1]? arg[1][0] : 0;
  a0=(a0+a1);
  if (res[0]!=0) res[0][2]=a0;
  a25=(a25*a18);
  a25=(a25+a17);
  a3=(a3*a23);
  a25=(a25-a3);
  a3=arg[1]? arg[1][1] : 0;
  a25=(a25+a3);
  if (res[0]!=0) res[0][3]=a25;
  if (res[0]!=0) res[0][4]=a9;
  a4=(a4-a9);
  if (res[0]!=0) res[0][5]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int double_joints_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int double_joints_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int double_joints_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void double_joints_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int double_joints_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void double_joints_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void double_joints_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void double_joints_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int double_joints_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int double_joints_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real double_joints_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* double_joints_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* double_joints_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* double_joints_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* double_joints_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int double_joints_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int double_joints_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
