/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) human_turbo_doc_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {5, 1, 1};
static const casadi_int casadi_s5[3] = {11, 1, 1};

/* human_turbo_doc_cost_y_0_fun:(i0[4],i1[2],i2[0],i3[],i4[5])->(o0[11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55;
  a00=1.4000000000000000e-02;
  a01=arg[1]? arg[1][0] : 0;
  a00=(a00*a01);
  a02=5.0000000000000001e-03;
  a03=1.8000000000000000e+00;
  a04=9.8100000000000005e+00;
  a05=arg[0]? arg[0][0] : 0;
  a06=cos(a05);
  a07=(a04*a06);
  a08=(a02*a01);
  a08=(a07+a08);
  a08=(a03*a08);
  a08=(a02*a08);
  a09=-1.2500000000000000e-01;
  a10=sin(a05);
  a11=(a04*a10);
  a12=(a09*a01);
  a12=(a11-a12);
  a03=(a03*a12);
  a03=(a09*a03);
  a08=(a08-a03);
  a00=(a00+a08);
  a08=4.6511817341040457e-02;
  a03=arg[1]? arg[1][1] : 0;
  a12=(a03+a01);
  a13=(a08*a12);
  a14=6.1213872832369953e-03;
  a15=1.7300000000000000e+00;
  a16=arg[0]? arg[0][3] : 0;
  a17=arg[0]? arg[0][1] : 0;
  a18=cos(a17);
  a19=-2.7600000000000002e-01;
  a20=arg[0]? arg[0][2] : 0;
  a21=(a19*a20);
  a22=(a18*a21);
  a23=(a16*a22);
  a24=(a18*a07);
  a25=sin(a17);
  a26=(a19*a01);
  a11=(a11-a26);
  a27=(a25*a11);
  a24=(a24-a27);
  a24=(a23+a24);
  a27=(a14*a12);
  a24=(a24+a27);
  a24=(a15*a24);
  a27=(a14*a24);
  a28=-2.0323699421965319e-01;
  a21=(a25*a21);
  a29=(a16*a21);
  a11=(a18*a11);
  a07=(a25*a07);
  a11=(a11+a07);
  a11=(a29+a11);
  a07=(a28*a12);
  a11=(a11-a07);
  a11=(a15*a11);
  a07=(a28*a11);
  a27=(a27-a07);
  a13=(a13+a27);
  a27=(a16+a20);
  a07=(a28*a27);
  a07=(a22+a07);
  a07=(a15*a07);
  a30=(a21*a07);
  a31=(a14*a27);
  a31=(a21+a31);
  a31=(a15*a31);
  a32=(a22*a31);
  a30=(a30-a32);
  a13=(a13+a30);
  a31=(a27*a31);
  a11=(a11-a31);
  a11=(a18*a11);
  a07=(a27*a07);
  a24=(a24-a07);
  a24=(a25*a24);
  a11=(a11-a24);
  a11=(a19*a11);
  a11=(a13-a11);
  a00=(a00+a11);
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a13;
  a13=1.1219893200000003e+01;
  a00=3.4629300000000008e+01;
  a11=5.0991501416430596e-01;
  a24=3.2400000000000007e-01;
  a07=(a02*a10);
  a31=(a09*a06);
  a30=-1.5543122344752192e-18;
  a31=(a31+a30);
  a07=(a07+a31);
  a07=(a24+a07);
  a07=(a11*a07);
  a31=4.9008498583569404e-01;
  a30=(a19*a06);
  a30=(a24+a30);
  a32=(a10*a18);
  a33=(a06*a25);
  a34=(a32+a33);
  a35=(a14*a34);
  a36=(a06*a18);
  a37=(a10*a25);
  a36=(a36-a37);
  a37=(a28*a36);
  a38=1.4657510914704380e-18;
  a37=(a37+a38);
  a35=(a35+a37);
  a35=(a30+a35);
  a37=(a31*a35);
  a07=(a07+a37);
  a07=(a00*a07);
  a37=2.2204460492503131e-16;
  a38=-2.0999999999999991e-01;
  a39=(a37*a10);
  a02=(a02*a39);
  a06=(a37*a06);
  a09=(a09*a06);
  a40=7.0000000000000001e-03;
  a09=(a09+a40);
  a02=(a02+a09);
  a02=(a38+a02);
  a11=(a11*a02);
  a02=(a19*a06);
  a02=(a38+a02);
  a09=(a39*a18);
  a40=(a06*a25);
  a09=(a09+a40);
  a40=(a14*a09);
  a06=(a06*a18);
  a39=(a39*a25);
  a06=(a06-a39);
  a39=(a28*a06);
  a41=-6.6011560693641624e-03;
  a39=(a39+a41);
  a40=(a40+a39);
  a40=(a02+a40);
  a31=(a31*a40);
  a11=(a11+a31);
  a00=(a00*a11);
  a00=(a37*a00);
  a07=(a07+a00);
  a13=(a13-a07);
  a13=(a13*a20);
  a07=3.2400000000000001e-01;
  a00=8.0000000000000002e-03;
  a19=(a19*a10);
  a19=(a00-a19);
  a10=(a01*a19);
  a11=(a37*a01);
  a31=(a37*a19);
  a39=(a11*a31);
  a10=(a10+a39);
  a39=(a00*a11);
  a39=(a37*a39);
  a41=(a00*a01);
  a42=-9.8100000000000005e+00;
  a41=(a41+a42);
  a39=(a39+a41);
  a10=(a10-a39);
  a39=(a37*a02);
  a39=(a39+a30);
  a41=(a20*a39);
  a43=(a37*a20);
  a44=(a38*a43);
  a45=(a24*a20);
  a44=(a44+a45);
  a41=(a41-a44);
  a45=(a20*a41);
  a46=(a43*a39);
  a44=(a37*a44);
  a46=(a46-a44);
  a44=(a43*a46);
  a45=(a45+a44);
  a10=(a10-a45);
  a10=(a15*a10);
  a18=(a18*a26);
  a29=(a29-a18);
  a18=(a34*a29);
  a25=(a25*a26);
  a23=(a23+a25);
  a25=(a36*a23);
  a18=(a18+a25);
  a25=(a19*a12);
  a18=(a18-a25);
  a18=(a18-a42);
  a14=(a14*a36);
  a33=(a33+a32);
  a28=(a28*a33);
  a14=(a14-a28);
  a14=(a19+a14);
  a28=(a14*a12);
  a18=(a18+a28);
  a18=(a15*a18);
  a28=(a37*a27);
  a32=(a02*a28);
  a42=(a30*a27);
  a32=(a32+a42);
  a42=(a36*a22);
  a25=(a33*a21);
  a42=(a42+a25);
  a32=(a32-a42);
  a42=(a40*a28);
  a25=(a35*a27);
  a42=(a42+a25);
  a42=(a32-a42);
  a42=(a15*a42);
  a25=(a27*a42);
  a25=(a18+a25);
  a26=(a09*a29);
  a45=(a06*a23);
  a26=(a26+a45);
  a45=(a37*a12);
  a44=(a19*a45);
  a26=(a26-a44);
  a44=(a14*a45);
  a26=(a26+a44);
  a26=(a15*a26);
  a44=(a28*a42);
  a44=(a26+a44);
  a47=(a37*a44);
  a47=(a25+a47);
  a47=(a10-a47);
  a07=(a07*a47);
  a47=-1.7763568394002505e-18;
  a48=(a11*a39);
  a38=(a38*a11);
  a24=(a24*a01);
  a38=(a38+a24);
  a24=(a37*a38);
  a48=(a48-a24);
  a24=(a20*a19);
  a11=(a43*a31);
  a24=(a24+a11);
  a11=(a00*a43);
  a11=(a37*a11);
  a00=(a00*a20);
  a11=(a11+a00);
  a24=(a24-a11);
  a43=(a43*a24);
  a48=(a48+a43);
  a48=(a15*a48);
  a29=(a36*a29);
  a23=(a33*a23);
  a29=(a29-a23);
  a02=(a02*a45);
  a30=(a30*a12);
  a02=(a02+a30);
  a29=(a29+a02);
  a02=(a40*a45);
  a30=(a35*a12);
  a02=(a02+a30);
  a29=(a29-a02);
  a29=(a15*a29);
  a02=(a36*a21);
  a30=(a34*a22);
  a02=(a02-a30);
  a30=(a19*a27);
  a02=(a02-a30);
  a30=(a14*a27);
  a30=(a02+a30);
  a30=(a15*a30);
  a23=(a27*a30);
  a21=(a06*a21);
  a22=(a09*a22);
  a21=(a21-a22);
  a22=(a19*a28);
  a21=(a21-a22);
  a22=(a14*a28);
  a22=(a21+a22);
  a22=(a15*a22);
  a43=(a28*a22);
  a23=(a23+a43);
  a29=(a29-a23);
  a23=(a37*a29);
  a23=(a48+a23);
  a47=(a47*a23);
  a23=-8.0000000000000002e-03;
  a43=(a01*a39);
  a43=(a43-a38);
  a38=(a20*a24);
  a43=(a43+a38);
  a43=(a15*a43);
  a38=(a43+a29);
  a23=(a23*a38);
  a47=(a47+a23);
  a07=(a07+a47);
  a47=(a15*a21);
  a23=(a15*a28);
  a38=(a14*a23);
  a47=(a47+a38);
  a47=(a22-a47);
  a47=(a47*a24);
  a32=(a15*a32);
  a38=(a40*a23);
  a38=(a32-a38);
  a11=(a15*a27);
  a00=(a11*a35);
  a38=(a38-a00);
  a38=(a38-a42);
  a38=(a38*a46);
  a46=(a23*a35);
  a00=(a35*a23);
  a49=(a40*a11);
  a49=(a00-a49);
  a49=(a46-a49);
  a50=(a11*a40);
  a46=(a46-a50);
  a00=(a00-a46);
  a49=(a49-a00);
  a49=(a49*a41);
  a38=(a38+a49);
  a47=(a47+a38);
  a38=(a14*a48);
  a49=(a40*a10);
  a38=(a38-a49);
  a47=(a47+a38);
  a38=1.4453502890173428e-03;
  a49=(a38*a34);
  a00=2.0985202312138727e-03;
  a46=(a00*a36);
  a50=1.5101086726623980e-19;
  a46=(a46+a50);
  a49=(a49+a46);
  a46=(a49*a36);
  a50=(a00*a34);
  a51=-4.3000578034682074e-02;
  a52=(a51*a36);
  a53=-9.0845763795339256e-20;
  a52=(a52+a53);
  a50=(a50+a52);
  a52=(a50*a33);
  a46=(a46-a52);
  a52=3.4004624277456650e-04;
  a53=(a52*a06);
  a54=-2.0456647398843899e-04;
  a55=(a54*a09);
  a53=(a53-a55);
  a46=(a46-a53);
  a46=(a46*a45);
  a38=(a38*a09);
  a45=(a00*a06);
  a53=-6.8009248554913300e-04;
  a45=(a45+a53);
  a38=(a38+a45);
  a45=(a38*a36);
  a00=(a00*a09);
  a51=(a51*a06);
  a53=4.0913294797687797e-04;
  a51=(a51+a53);
  a00=(a00+a51);
  a51=(a00*a33);
  a45=(a45-a51);
  a51=(a52*a36);
  a53=(a54*a34);
  a51=(a51-a53);
  a45=(a45+a51);
  a45=(a45*a12);
  a46=(a46-a45);
  a18=(a40*a18);
  a26=(a35*a26);
  a18=(a18-a26);
  a46=(a46+a18);
  a21=(a21*a30);
  a18=(a02*a22);
  a21=(a21-a18);
  a34=(a49*a34);
  a18=(a50*a36);
  a34=(a34+a18);
  a34=(a34+a08);
  a34=(a34*a28);
  a49=(a49*a09);
  a50=(a50*a06);
  a49=(a49+a50);
  a54=(a54*a36);
  a52=(a52*a33);
  a54=(a54+a52);
  a49=(a49-a54);
  a54=(a49*a27);
  a34=(a34-a54);
  a22=(a14*a22);
  a54=(a40*a42);
  a22=(a22-a54);
  a34=(a34+a22);
  a34=(a27*a34);
  a49=(a49*a28);
  a38=(a38*a09);
  a00=(a00*a06);
  a38=(a38+a00);
  a38=(a38+a08);
  a38=(a38*a27);
  a49=(a49-a38);
  a38=(a35*a42);
  a27=(a14*a30);
  a38=(a38-a27);
  a49=(a49+a38);
  a28=(a28*a49);
  a34=(a34+a28);
  a21=(a21-a34);
  a46=(a46+a21);
  a44=(a39*a44);
  a21=(a31*a29);
  a44=(a44+a21);
  a44=(a46+a44);
  a44=(a47+a44);
  a44=(a37*a44);
  a02=(a15*a02);
  a21=(a14*a11);
  a02=(a02+a21);
  a02=(a02-a30);
  a02=(a02*a24);
  a11=(a35*a11);
  a11=(a11-a32);
  a23=(a23*a40);
  a11=(a11+a23);
  a11=(a11+a42);
  a11=(a11*a41);
  a02=(a02+a11);
  a11=(a35*a10);
  a14=(a14*a43);
  a11=(a11-a14);
  a02=(a02+a11);
  a46=(a37*a46);
  a29=(a19*a29);
  a25=(a39*a25);
  a29=(a29+a25);
  a46=(a46-a29);
  a46=(a02+a46);
  a44=(a44-a46);
  a07=(a07+a44);
  a07=(a07*a16);
  a13=(a13+a07);
  if (res[0]!=0) res[0][2]=a13;
  a40=(a37*a40);
  a40=(a40+a35);
  a40=(a39-a40);
  a15=(a15*a40);
  a04=(a04*a15);
  a04=(a04*a20);
  a39=(a39*a10);
  a31=(a31*a48);
  a43=(a19*a43);
  a31=(a31+a43);
  a39=(a39-a31);
  a37=(a37*a47);
  a37=(a37-a02);
  a39=(a39+a37);
  a39=(a39*a16);
  a04=(a04+a39);
  if (res[0]!=0) res[0][3]=a04;
  if (res[0]!=0) res[0][4]=a01;
  if (res[0]!=0) res[0][5]=a03;
  if (res[0]!=0) res[0][6]=a20;
  if (res[0]!=0) res[0][7]=a16;
  if (res[0]!=0) res[0][8]=a05;
  if (res[0]!=0) res[0][9]=a17;
  a17=-2.8699999999999998e-01;
  a17=(a17*a33);
  a19=(a19-a17);
  a17=arg[4]? arg[4][2] : 0;
  a19=(a19-a17);
  if (res[0]!=0) res[0][10]=a19;
  return 0;
}

CASADI_SYMBOL_EXPORT int human_turbo_doc_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int human_turbo_doc_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int human_turbo_doc_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void human_turbo_doc_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int human_turbo_doc_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void human_turbo_doc_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void human_turbo_doc_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void human_turbo_doc_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int human_turbo_doc_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int human_turbo_doc_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real human_turbo_doc_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* human_turbo_doc_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* human_turbo_doc_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* human_turbo_doc_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* human_turbo_doc_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int human_turbo_doc_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int human_turbo_doc_cost_y_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
